language: c
 
install:
  - sudo apt-get install mono-devel mono-gmcs nunit-console
 
script:
  - mono --runtime=v4.0.30319 "/home/travis/build/confa/Azimuth/.nuget/NuGet.exe" restore Azimuth.sln
  - xbuild Azimuth.sln
